version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    # Add these recommended settings
    allow:
      # Only handle production dependencies by default
      - dependency-type: "production"
    commit-message:
      prefix: "deps"
      include: "scope"
    # Group updates together
    groups:
      dev-dependencies:
        patterns:
          - "black"
          - "isort"
          - "flake8"
          - "mypy"
          - "bandit"
          - "pytest*"
      production-dependencies:
        patterns:
          - "streamlit"
          - "pandas"
          - "altair"
          - "google-cloud-firestore"
    # Specify target branch
    target-branch: "main"
    # Set reviewers for the PRs
    reviewers:
      - "444B"
    # Labels for PRs
    labels:
      - "dependencies"
      - "automated"