name: Build and Publish

on:
  push:
    branches:
      - 'main'
      - 'test/**'

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # For complete history if needed for versioning
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      
      - name: Install build tools
        run: |
          pip install uv
          uv venv
          source .venv/bin/activate
          uv pip install hatch build twine
      
      - name: Build package
        run: python -m build
      
      - name: Upload to TestPyPI
        if: contains(github.ref, 'refs/heads/test/')
        uses: pypa/gh-action-pypi-publish@v1.8.11
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          verbose: true
          verify_metadata: true
          skip_existing: true
      
      - name: Upload to PyPI
        if: github.ref == 'refs/heads/main'
        uses: pypa/gh-action-pypi-publish@v1.8.11
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true
          verify_metadata: true